export const friendlyRoutingNames: Record<string, string> = {
  konto: "Moje konto",
  "ksiazka-adresowa": "Książka adresowa",
  zamowienia: "Moje zamówienia",
  "zmiana-email": "Zmiana email",
  "zmiana-hasla": "Zmiana hasła",
  "edytuj-dane": "Edytuj dane",
  "zarzadzanie-produktami": "Zarządzanie produktami",
  "zarzadzanie-zamowieniami": "Zarządzanie zamówieniami",
  "zarzadzanie-uzytkownikami": "Zarządzanie użytkownikami",
  admin: "Panel administracyjny",
  "edycja-uzytkownika": "Edycja użytkownika",
  "dodaj-uzytkownika": "Dodaj użytkownika",
  "dodaj-adres": "Dodaj adres",
};
